#!/bin/bash

#######################################
# Calendly Clone - One Command Setup
# Run this script to start the app!
#######################################

set -e

# Colors for pretty output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print functions
print_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}→ $1${NC}"
}

# Check for Node.js
check_node() {
    print_info "Checking for Node.js..."
    if ! command -v node &> /dev/null; then
        print_error "Node.js is not installed!"
        echo ""
        echo "Please install Node.js first:"
        echo "  - Download from: https://nodejs.org/"
        echo "  - Recommended: Use the LTS (Long Term Support) version"
        echo ""
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        print_warning "Node.js version is $NODE_VERSION. Recommended: 18 or higher."
    else
        print_success "Node.js $(node -v) found"
    fi
}

# Check for npm
check_npm() {
    print_info "Checking for npm..."
    if ! command -v npm &> /dev/null; then
        print_error "npm is not installed!"
        echo "npm should come with Node.js. Please reinstall Node.js."
        exit 1
    fi
    print_success "npm $(npm -v) found"
}

# Get script directory (where setup.sh is located)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"

# Main setup
print_header "Calendly Clone Setup"
echo "This script will set up and start your personal scheduling app."
echo ""

# Check dependencies
check_node
check_npm

# Setup Backend
print_header "Setting Up Backend"

cd "$SCRIPT_DIR/backend"

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    print_info "Creating environment configuration..."

    # Generate random secrets
    JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    CSRF_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")

    cat > .env << EOF
# Calendly Clone Configuration
# Generated by setup script on $(date)

# Server
PORT=3001
NODE_ENV=production

# Security (auto-generated - keep these secret!)
JWT_SECRET=$JWT_SECRET
CSRF_SECRET=$CSRF_SECRET

# Email notifications (optional - add your SMTP details to enable)
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASS=your-app-password
# EMAIL_FROM=Your Name <your-email@gmail.com>

# URL where the app will be accessed (update for production)
APP_URL=http://localhost:5173
EOF
    print_success "Environment configuration created"
else
    print_success "Environment configuration already exists"
fi

# Install backend dependencies
print_info "Installing backend dependencies (this may take a minute)..."
npm install --silent 2>/dev/null || npm install
print_success "Backend dependencies installed"

# Setup Frontend
print_header "Setting Up Frontend"

cd "$SCRIPT_DIR/frontend"

# Install frontend dependencies
print_info "Installing frontend dependencies (this may take a minute)..."
npm install --silent 2>/dev/null || npm install
print_success "Frontend dependencies installed"

# Start the application
print_header "Starting Application"

cd "$SCRIPT_DIR"

# Kill any existing processes on our ports
print_info "Cleaning up old processes..."
lsof -ti:3001 | xargs kill -9 2>/dev/null || true
lsof -ti:5173 | xargs kill -9 2>/dev/null || true

# Start backend in background
print_info "Starting backend server..."
cd "$SCRIPT_DIR/backend"
npm start > /dev/null 2>&1 &
BACKEND_PID=$!

# Wait for backend to be ready
sleep 3
if ! kill -0 $BACKEND_PID 2>/dev/null; then
    print_error "Backend failed to start"
    exit 1
fi
print_success "Backend running (PID: $BACKEND_PID)"

# Start frontend
print_info "Starting frontend..."
cd "$SCRIPT_DIR/frontend"
npm run dev > /dev/null 2>&1 &
FRONTEND_PID=$!

# Wait for frontend to be ready
sleep 3
if ! kill -0 $FRONTEND_PID 2>/dev/null; then
    print_error "Frontend failed to start"
    kill $BACKEND_PID 2>/dev/null
    exit 1
fi
print_success "Frontend running (PID: $FRONTEND_PID)"

# Done!
print_header "Setup Complete!"

echo -e "${GREEN}Your Calendly Clone is now running!${NC}"
echo ""
echo "📱 Admin Panel:    http://localhost:5173"
echo "📅 Booking Page:   http://localhost:5173/book"
echo ""
echo -e "${YELLOW}First Time Setup:${NC}"
echo "1. Go to http://localhost:5173"
echo "2. Create your admin account"
echo "3. Set up your availability"
echo "4. Share your booking link!"
echo ""
echo -e "${YELLOW}To stop the app:${NC}"
echo "  Press Ctrl+C or run: ./stop.sh"
echo ""

# Save PIDs for stop script
echo "$BACKEND_PID" > "$SCRIPT_DIR/.backend.pid"
echo "$FRONTEND_PID" > "$SCRIPT_DIR/.frontend.pid"

# Wait for user to press Ctrl+C
trap "kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; rm -f $SCRIPT_DIR/.backend.pid $SCRIPT_DIR/.frontend.pid; echo -e '\n${GREEN}App stopped. Goodbye!${NC}'; exit 0" INT

# Keep script running
wait
